import { Noto_Sans } from "next/font/google";  
import "./globals.css";

const notoSans = Noto_Sans({ subsets: ["latin"] });   

export const metadata = {
  title: "OCR Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notoSans.className}>{children}</body>   
    </html>
  );
}
